version: "3"
services:
  nginx:
    container_name: nginx-api
    image: nginx-api:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - fastapi-rest-api
      - flask-rest-api
  fastapi-rest-api:
    container_name: fastapi-rest-api
    # Remove the build command for configuration file in azure web app service
    image: fastapi-rest-api:latest
    ports:
      - 8000:5000
  flask-rest-api:
    container_name: flask-rest-api
    image: flask-rest-api:latest
    ports:
      - 7000:5000